## download files

```{r}
setwd("/scratch/iacs/tmp/illumina_platinum/")
mat = read.table("/scratch/iacs/tmp/illumina_platinum/ERP001775_illumina_platinum.txt", 
                 sep = "\t", header = TRUE, stringsAsFactors = FALSE)

fqs = unlist(strsplit(mat$fastq_ftp, ";"))
fqs = paste0("ftp://", fqs)

require(parallel)
# tmp <- lapply(fqs, function(fq){
#   download.file(fq, basename(fq))
# })
#, mc.cores = 1


fqs = unlist(strsplit(mat$fastq_ftp, ";"))
fqs_asp = gsub("ftp.sra.ebi.ac.uk", "fasp.sra.ebi.ac.uk:",fqs)
key = "/IACS1/apps/aspera/connect/etc/asperaweb_id_dsa.openssh"

# fq = "fasp.sra.ebi.ac.uk:/vol1/fastq/ERR036/ERR036000/ERR036000_1.fastq.gz"
# fq = "fasp.sra.ebi.ac.uk/vol1/fastq/ERR174/ERR174377/ERR174377_2.fastq.gz"
tmp <- mclapply(fqs_asp, function(fq){
  cmd <- sprintf("ascp -QT -l 300m -i %s era-fasp@%s %s",
                 key, fq, getwd())
  system(cmd)
  }, mc.cores = 6)


```



```{r download.vcfs}
library(RCurl) 
# Download the files for 1985. 
#url = "ftp://ftp.cpc.ncep.noaa.gov/fews/AFR_CLIM/ARC2/DATA/1985/" 
url = "ftp://platgene:G3n3s4me@ussd-ftp.illumina.com/"
filenames = getURL(url, dirlistonly = TRUE) 
fn <- unlist(strsplit(filenames, "\n")) 
destdir = "/scratch/iacs/tmp/illumina_platinum/"
lapply(fn, function(x) download.file(paste0(url, x), paste0(destdir, x))) 


crlf = TRUE 
```

